/*
u Calculate e
Time Limit: 2000/1000 MS (Java/Others)    Memory Limit: 65536/32768 K (Java/Others)
Total Submission(s): 61977    Accepted Submission(s): 28359


Problem Description
A simple mathematical formula for e is
     n   1
e =  ¡Æ  ---
    i=0  i!
where n is allowed to go to infinity.
This can actually yield very accurate approximations of
e using relatively small values of n.


Output
Output the approximations of e generated by the above
formula for the values of n from 0 to 9.
The beginning of your output should appear similar to that shown below.
*/
#include <iostream>
#include <cstdio>
using namespace std;
int main()
{
	int a = 1;
	double e = 1;
	printf("n e\n- -----------\n");
	printf("0 1\n");
	// calculate & output
	for(int n = 1; n <= 9; n++)
	{
		a=n*a;
		e+=1.0/a;
		if(n==1)
		printf("%d %.0lf\n",n,e);
		else if(n==2)
		printf("%d %.1lf\n",n,e);
		else
		printf("%d %.9lf\n",n,e);
	}
	return 0;
 }
